{"version":3,"sources":["asap.js"],"names":["rawAsap","require","freeTasks","module","exports","asap","task","rawTask","length","pop","RawTask","domain","process","prototype","call","enter","threw","exit","requestFlush","push"],"mappings":"AAAA;;AAEA,IAAIA,OAAO,GAAGC,OAAO,CAAC,OAAD,CAArB;;AACA,IAAIC,SAAS,GAAG,EAAhB;AAYAC,MAAM,CAACC,OAAP,GAAiBC,IAAjB;;AACA,SAASA,IAAT,CAAcC,IAAd,EAAoB;AAChB,MAAIC,OAAJ;;AACA,MAAIL,SAAS,CAACM,MAAd,EAAsB;AAClBD,IAAAA,OAAO,GAAGL,SAAS,CAACO,GAAV,EAAV;AACH,GAFD,MAEO;AACHF,IAAAA,OAAO,GAAG,IAAIG,OAAJ,EAAV;AACH;;AACDH,EAAAA,OAAO,CAACD,IAAR,GAAeA,IAAf;AACAC,EAAAA,OAAO,CAACI,MAAR,GAAiBC,OAAO,CAACD,MAAzB;AACAX,EAAAA,OAAO,CAACO,OAAD,CAAP;AACH;;AAED,SAASG,OAAT,GAAmB;AACf,OAAKJ,IAAL,GAAY,IAAZ;AACA,OAAKK,MAAL,GAAc,IAAd;AACH;;AAEDD,OAAO,CAACG,SAAR,CAAkBC,IAAlB,GAAyB,YAAY;AACjC,MAAI,KAAKH,MAAT,EAAiB;AACb,SAAKA,MAAL,CAAYI,KAAZ;AACH;;AACD,MAAIC,KAAK,GAAG,IAAZ;;AACA,MAAI;AACA,SAAKV,IAAL,CAAUQ,IAAV;AACAE,IAAAA,KAAK,GAAG,KAAR;;AAGA,QAAI,KAAKL,MAAT,EAAiB;AACb,WAAKA,MAAL,CAAYM,IAAZ;AACH;AACJ,GARD,SAQU;AAGN,QAAID,KAAJ,EAAW;AAMPhB,MAAAA,OAAO,CAACkB,YAAR;AACH;;AAGD,SAAKZ,IAAL,GAAY,IAAZ;AACA,SAAKK,MAAL,GAAc,IAAd;AACAT,IAAAA,SAAS,CAACiB,IAAV,CAAe,IAAf;AACH;AACJ,CA9BD","sourcesContent":["\"use strict\";\n\nvar rawAsap = require(\"./raw\");\nvar freeTasks = [];\n\n/**\n * Calls a task as soon as possible after returning, in its own event, with\n * priority over IO events. An exception thrown in a task can be handled by\n * `process.on(\"uncaughtException\") or `domain.on(\"error\")`, but will otherwise\n * crash the process. If the error is handled, all subsequent tasks will\n * resume.\n *\n * @param {{call}} task A callable object, typically a function that takes no\n * arguments.\n */\nmodule.exports = asap;\nfunction asap(task) {\n    var rawTask;\n    if (freeTasks.length) {\n        rawTask = freeTasks.pop();\n    } else {\n        rawTask = new RawTask();\n    }\n    rawTask.task = task;\n    rawTask.domain = process.domain;\n    rawAsap(rawTask);\n}\n\nfunction RawTask() {\n    this.task = null;\n    this.domain = null;\n}\n\nRawTask.prototype.call = function () {\n    if (this.domain) {\n        this.domain.enter();\n    }\n    var threw = true;\n    try {\n        this.task.call();\n        threw = false;\n        // If the task throws an exception (presumably) Node.js restores the\n        // domain stack for the next event.\n        if (this.domain) {\n            this.domain.exit();\n        }\n    } finally {\n        // We use try/finally and a threw flag to avoid messing up stack traces\n        // when we catch and release errors.\n        if (threw) {\n            // In Node.js, uncaught exceptions are considered fatal errors.\n            // Re-throw them to interrupt flushing!\n            // Ensure that flushing continues if an uncaught exception is\n            // suppressed listening process.on(\"uncaughtException\") or\n            // domain.on(\"error\").\n            rawAsap.requestFlush();\n        }\n        // If the task threw an error, we do not want to exit the domain here.\n        // Exiting the domain would prevent the domain from catching the error.\n        this.task = null;\n        this.domain = null;\n        freeTasks.push(this);\n    }\n};\n\n"]}